// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1zbNNE71mcDPhNnDBDpzTCqrzcoEJqoc',
    appId: '1:1097985768380:web:cd3297c26c5468979049b9',
    messagingSenderId: '1097985768380',
    projectId: 'safetify-61721',
    authDomain: 'safetify-61721.firebaseapp.com',
    storageBucket: 'safetify-61721.firebasestorage.app',
    measurementId: 'G-92F38PLY2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUeIzllAdqOC8P9RjkE3hKcdQgQz3xT60',
    appId: '1:1097985768380:android:e1f6241746a88e449049b9',
    messagingSenderId: '1097985768380',
    projectId: 'safetify-61721',
    storageBucket: 'safetify-61721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQDphduPxRA00YIDTyrXHOY-h4XYsupCI',
    appId: '1:1097985768380:ios:7f2b0c8f26088bf79049b9',
    messagingSenderId: '1097985768380',
    projectId: 'safetify-61721',
    storageBucket: 'safetify-61721.firebasestorage.app',
    iosBundleId: 'com.example.safetify',
  );

}